### ISSUE TITLE
MinGW python package should depend on mingw-w64-ca-certificates

### ISSUE THREAD

**Issue by fracting** [Alexpux/MINGW-packages#1086]
This is detected by our CI server: http://wine-ci.org/Alexpux/MINGW-packages/78

```
Download error on https://pypi.python.org/simple/pkgconfig/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
```

I originally thought it was a Wine bug, and reported it as https://bugs.wine-staging.com/show_bug.cgi?id=649

Thanks to @vszakats ( https://github.com/Alexpux/MINGW-packages/pull/1077#issuecomment-187007481 ) I took a look at the Wine log and found python was looking for C:/msys32/mingw32/ssl/cert.pem but it was missing. Then I do a fresh installation on Windows and found the same file is missing on Windows as well even after install MINGW python.

This file is part of mingw-w64-ca-certificates. If we don't set dependencies on it, our CI server won't automatically install this package when install python, and such a simple test case will fail:

```
$ python2
Python 2.7.10 (default, Jul  8 2015, 15:14:56)
[GCC 5.1.0] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> urllib2.urlopen("https://www.baidu.com")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys32/mingw32/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:/msys32/mingw32/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:/msys32/mingw32/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "C:/msys32/mingw32/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:/msys32/mingw32/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:/msys32/mingw32/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

**Comment by Alexpux** [comment]
See my comment

**Comment by fracting** [comment]
Fixed, tested with http://wine-ci.org/fracting/MINGW-packages/36

**Comment by iongion** [comment]
Still having this and I did not find any way to fix it or to find where it comes from.
Event with this downloaded and set as below, it still shows the HTTPS issue
`export PIP_CERT="/mingw64/ssl/DigiCertHighAssuranceEVRootCA.pem"`

All my installed packages are:

```
autoconf 2.69-3
autoconf2.13 2.13-2
autogen 5.18.4-2
automake-wrapper 10-1
automake1.10 1.10.3-3
automake1.11 1.11.6-3
automake1.12 1.12.6-3
automake1.13 1.13.4-4
automake1.14 1.14.1-3
automake1.15 1.15-2
automake1.6 1.6.3-2
automake1.7 1.7.9-2
automake1.8 1.8.5-3
automake1.9 1.9.6-2
bash 4.3.046-1
bash-completion 2.3-1
binutils 2.25.1-2
bison 3.0.4-1
bsdcpio 3.2.1-1
bsdtar 3.2.1-1
bzip2 1.0.6-2
ca-certificates 20150426-1
catgets 1.1-2
clang-svn 60106.1d5b05f-1
cloog 0.18.3-1
cmake 3.6.2-1
cocom 0.996-2
coreutils 8.25-1
crypt 1.3-1
curl 7.50.3-1
dash 0.5.8-1
db 5.3.28-2
diffstat 1.58-1
diffutils 3.3-3
dos2unix 7.3.4-1
expat 2.2.0-1
file 5.25-1
filesystem 2016.07-2
findutils 4.6.0-1
flex 2.6.1-1
gawk 4.1.4-1
gcc 5.3.0-3
gcc-fortran 5.3.0-3
gcc-libs 5.3.0-3
gdbm 1.11-3
gettext 0.19.7-3
git 2.9.1-1
glib2 2.48.0-1
gmp 6.1.0-2
gnupg 1.4.20-1
gperf 3.0.4-3
grep 2.22-3
groff 1.22.3-1
gzip 1.7-1
heimdal 1.5.3-9
heimdal-libs 1.5.3-9
help2man 1.47.3-1
icu 56.1-1
inetutils 1.9.2-1
info 6.1-1
intltool 0.51.0-2
isl 0.16.1-1
lemon 3.8.7.0-1
less 481-1
libarchive 3.2.1-1
libasprintf 0.19.7-3
libassuan 2.4.2-1
libbz2 1.0.6-2
libcatgets 1.1-2
libcrypt 1.3-1
libcrypt-devel 1.3-1
libcurl 7.50.3-1
libdb 5.3.28-2
libedit 3.1-20150325
libexpat 2.2.0-1
libffi 3.2.1-1
libgc 7.2.d-1
libgcrypt 1.6.4-1
libgdbm 1.11-3
libgettextpo 0.19.7-3
libgpg-error 1.23-1
libgpgme 1.6.0-1
libguile 2.0.11-3
libiconv 1.14-2
libidn 1.33-1
libintl 0.19.7-3
libltdl 2.4.6-2
liblzma 5.2.2-1
liblzo2 2.09-1
libmetalink 0.1.2-2
libnettle 3.2-1
libopenssl 1.0.2.h-1
libp11-kit 0.23.2-1
libpcre 8.38-1
libpcre16 8.38-1
libpcre32 8.38-1
libpcrecpp 8.38-1
libpcreposix 8.38-1
libpipeline 1.4.0-1
libreadline 6.3.008-7
libsqlite 3.10.0.0-1
libssh2 1.7.0-1
libtasn1 4.9-1
libtool 2.4.6-2
libunistring 0.9.6-1
libunrar 5.3.7-1
libutil-linux 2.26.2-1
libxml2 2.9.2-2
libxslt 1.1.28-7
llvm-svn 124592.2aebced-1
lndir 1.0.3-1
m4 1.4.17-4
make 4.2.1-1
man-db 2.7.4-1
mc 4.8.16-1
mingw-w64-i686-binutils 2.25.1-7
mingw-w64-i686-bzip2 1.0.6-5
mingw-w64-i686-cairo 1.15.2-4
mingw-w64-i686-crt-git 5.0.0.4735.9877f24-1
mingw-w64-i686-eigen3 3.2.8-1
mingw-w64-i686-expat 2.2.0-1
mingw-w64-i686-fontconfig 2.12.0-2
mingw-w64-i686-freetype 2.7-1
mingw-w64-i686-gcc 6.2.0-1
mingw-w64-i686-gcc-ada 6.2.0-1
mingw-w64-i686-gcc-libgfortran 6.2.0-1
mingw-w64-i686-gcc-libs 6.2.0-1
mingw-w64-i686-gettext 0.19.7-1
mingw-w64-i686-glib2 2.48.2-1
mingw-w64-i686-gmp 6.1.1-1
mingw-w64-i686-graphite2 1.3.8-5
mingw-w64-i686-harfbuzz 1.2.7-2
mingw-w64-i686-headers-git 5.0.0.4735.9877f24-1
mingw-w64-i686-ilmbase 2.2.0-2
mingw-w64-i686-intel-tbb 4.4_20160526-1
mingw-w64-i686-isl 0.17.1-1
mingw-w64-i686-jasper 1.900.1-4
mingw-w64-i686-libffi 3.2.1-4
mingw-w64-i686-libiconv 1.14-5
mingw-w64-i686-libjpeg-turbo 1.4.2-2
mingw-w64-i686-libpng 1.6.24-1
mingw-w64-i686-libtiff 4.0.6-1
mingw-w64-i686-libwinpthread-git 5.0.0.4733.ae160b2-1
mingw-w64-i686-lua 5.3.2-1
mingw-w64-i686-lua-lpeg 0.12-2
mingw-w64-i686-lzo2 2.09-2
mingw-w64-i686-mpc 1.0.3-2
mingw-w64-i686-mpfr 3.1.4.p3-4
mingw-w64-i686-opencv 3.1.0-1
mingw-w64-i686-openexr 2.2.0-2
mingw-w64-i686-pcre 8.38-1
mingw-w64-i686-pixman 0.34.0-3
mingw-w64-i686-windows-default-manifest 6.4-2
mingw-w64-i686-wineditline 2.101-4
mingw-w64-i686-winpthreads-git 5.0.0.4733.ae160b2-1
mingw-w64-i686-xz 5.2.2-1
mingw-w64-i686-zlib 1.2.8-9
mingw-w64-x86_64-adwaita-icon-theme 3.20-1
mingw-w64-x86_64-atk 2.22.0-1
mingw-w64-x86_64-bzip2 1.0.6-5
mingw-w64-x86_64-ca-certificates 20150426-2
mingw-w64-x86_64-cairo 1.15.2-4
mingw-w64-x86_64-dbus 1.10.10-1
mingw-w64-x86_64-expat 2.2.0-1
mingw-w64-x86_64-fontconfig 2.12.0-2
mingw-w64-x86_64-freetype 2.7-1
mingw-w64-x86_64-gcc-libgfortran 6.2.0-1
mingw-w64-x86_64-gcc-libs 6.2.0-1
mingw-w64-x86_64-gdbm 1.12-1
mingw-w64-x86_64-gdk-pixbuf2 2.36.0-1
mingw-w64-x86_64-gettext 0.19.7-1
mingw-w64-x86_64-giflib 5.1.4-1
mingw-w64-x86_64-glib2 2.50.0-1
mingw-w64-x86_64-gmp 6.1.1-1
mingw-w64-x86_64-gnome-common 3.18.0-1
mingw-w64-x86_64-gobject-introspection-runtime 1.50.0-1
mingw-w64-x86_64-graphite2 1.3.8-5
mingw-w64-x86_64-gtk2 2.24.28-3
mingw-w64-x86_64-harfbuzz 1.3.1-1
mingw-w64-x86_64-hicolor-icon-theme 0.15-2
mingw-w64-x86_64-icu 57.1-1
mingw-w64-x86_64-icu-debug-libs 57.1-1
mingw-w64-x86_64-ilmbase 2.2.0-2
mingw-w64-x86_64-intel-tbb 4.4_20160526-1
mingw-w64-x86_64-jasper 1.900.1-4
mingw-w64-x86_64-lcms2 2.7-1
mingw-w64-x86_64-libcroco 0.6.11-1
mingw-w64-x86_64-libffi 3.2.1-4
mingw-w64-x86_64-libgcrypt 1.7.3-1
mingw-w64-x86_64-libglade 2.6.4-4
mingw-w64-x86_64-libgpg-error 1.24-1
mingw-w64-x86_64-libiconv 1.14-5
mingw-w64-x86_64-libjpeg-turbo 1.4.2-2
mingw-w64-x86_64-libmng 2.0.3-3
mingw-w64-x86_64-libpng 1.6.25-1
mingw-w64-x86_64-librsvg 2.40.16-2
mingw-w64-x86_64-libsystre 1.0.1-2
mingw-w64-x86_64-libtasn1 4.9-1
mingw-w64-x86_64-libtiff 4.0.6-1
mingw-w64-x86_64-libtre-git r122.c2f5d13-4
mingw-w64-x86_64-libwebp 0.5.0-1
mingw-w64-x86_64-libwinpthread-git 5.0.0.4733.ae160b2-1
mingw-w64-x86_64-libxml2 2.9.4-2
mingw-w64-x86_64-libxslt 1.1.29-2
mingw-w64-x86_64-lua 5.3.2-1
mingw-w64-x86_64-lua-lpeg 0.12-2
mingw-w64-x86_64-lzo2 2.09-2
mingw-w64-x86_64-ncurses 6.0.20160917-1
mingw-w64-x86_64-openblas 0.2.17-1
mingw-w64-x86_64-opencv 3.1.0-1
mingw-w64-x86_64-openexr 2.2.0-2
mingw-w64-x86_64-openssl 1.0.2.h-1
mingw-w64-x86_64-p11-kit 0.23.2-2
mingw-w64-x86_64-pango 1.40.3-1
mingw-w64-x86_64-pcre 8.38-1
mingw-w64-x86_64-pixman 0.34.0-3
mingw-w64-x86_64-pygobject2-devel 2.28.6-3
mingw-w64-x86_64-pyqt5-common 5.6-1
mingw-w64-x86_64-python2 2.7.11-4
mingw-w64-x86_64-python2-cairo 1.10.0-2
mingw-w64-x86_64-python2-cjson 1.1.0-2
mingw-w64-x86_64-python2-cycler 0.9.0-1
mingw-w64-x86_64-python2-dateutil 2.5.2-1
mingw-w64-x86_64-python2-docutils 0.12-5
mingw-w64-x86_64-python2-gobject2 2.28.6-3
mingw-w64-x86_64-python2-matplotlib 1.5.1-1
mingw-w64-x86_64-python2-numpy 1.11.1-1
mingw-w64-x86_64-python2-pip 8.1.2-1
mingw-w64-x86_64-python2-pygtk 2.24.0-5
mingw-w64-x86_64-python2-pyparsing 2.0.3-2
mingw-w64-x86_64-python2-pyqt5 5.6-1
mingw-w64-x86_64-python2-pytz 2015.6-1
mingw-w64-x86_64-python2-scipy 0.18.1-1
mingw-w64-x86_64-python2-setuptools 27.3.0-1
mingw-w64-x86_64-python2-sip 4.18-1
mingw-w64-x86_64-python2-six 1.10.0-1
mingw-w64-x86_64-python3 3.5.2-1
mingw-w64-x86_64-qt5 5.6.1-3
mingw-w64-x86_64-qtbinpatcher 2.2.0-1
mingw-w64-x86_64-readline 6.3.008-1
mingw-w64-x86_64-shared-mime-info 1.4-2
mingw-w64-x86_64-sip 4.18-1
mingw-w64-x86_64-sqlite3 3.13.0-1
mingw-w64-x86_64-tcl 8.6.5-1
mingw-w64-x86_64-termcap 1.3.1-2
mingw-w64-x86_64-tk 8.6.5-1
mingw-w64-x86_64-wineditline 2.101-4
mingw-w64-x86_64-xpm-nox 4.2.0-4
mingw-w64-x86_64-xz 5.2.2-1
mingw-w64-x86_64-zlib 1.2.8-9
mintty 1~2.5.0-1
mpc 1.0.3-1
mpfr 3.1.4-1
msys2-keyring r9.397a52e-1
msys2-launcher-git 0.3.32.56c2ba7-2
msys2-runtime 2.6.0-1
msys2-runtime-devel 2.6.0-1
msys2-w32api-headers 5.0.0.4732.6172d2f-1
msys2-w32api-runtime 5.0.0.4732.6172d2f-1
ncurses 6.0.20160917-1
ncurses-devel 6.0.20160917-1
openssh 7.3p1-1
openssl 1.0.2.h-1
openssl-devel 1.0.2.h-1
p11-kit 0.23.2-1
pacman 5.0.1-1
pacman-mirrors 20160112-1
pactoys-git r2.07ca37f-1
patch 2.7.5-1
patchutils 0.3.4-1
pax-git 20140703.2.1.g469552a-1
pcre 8.38-1
pcre-devel 8.38-1
perl 5.22.1-1
perl-Authen-SASL 2.16-2
perl-Convert-BinHex 1.123-2
perl-Encode-Locale 1.04-1
perl-Error 0.17024-1
perl-File-Listing 6.04-2
perl-HTML-Parser 3.71-3
perl-HTML-Tagset 3.20-2
perl-HTTP-Cookies 6.01-2
perl-HTTP-Daemon 6.01-2
perl-HTTP-Date 6.02-2
perl-HTTP-Message 6.06-2
perl-HTTP-Negotiate 6.01-2
perl-IO-Socket-SSL 2.016-1
perl-IO-stringy 2.111-1
perl-LWP-MediaTypes 6.02-2
perl-Locale-Gettext 1.05-4
perl-MIME-tools 5.506-1
perl-MailTools 2.14-1
perl-Module-Build 0.4212-1
perl-Mozilla-CA 20141217-1
perl-Net-HTTP 6.09-1
perl-Net-SMTP-SSL 1.02-1
perl-Net-SSLeay 1.72-1
perl-TermReadKey 2.33-1
perl-Test-Pod 1.50-1
perl-TimeDate 2.30-2
perl-URI 1.68-1
perl-WWW-RobotRules 6.02-2
perl-XML-Parser 2.44-1
perl-YAML-Syck 1.29-1
perl-libwww 6.13-1
pkg-config 0.29.1-1
pkgfile 15-1
rcs 5.9.4-1
rebase 4.4.2-1
sed 4.2.2-2
ssh-pageant-git 1.4.4.gf09e76e-1
swig 3.0.10-1
tar 1.29-1
texinfo 6.1-1
texinfo-tex 6.1-1
tftp-hpa 5.2-1
time 1.7-1
tzcode 2015.e-1
ucl 1.03-1
unrar 5.3.7-1
upx 3.91-1
util-linux 2.26.2-1
vim 7.4.1721-1
wget 1.17.1-3
which 2.21-2
windows-default-manifest 6.4-1
winpty 0.2.2-2
xmlto 0.0.28-1
xz 5.2.2-1
zlib 1.2.8-3
zlib-devel 1.2.8-3
```
