### ISSUE TITLE
Links problem with wxWidgets 3.1

### ISSUE THREAD

**Issue by lpoujoulat** [Alexpux/MINGW-packages#1761]
The problem in #1712 is still present  with gcc 6.2 and crt 4735:

D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0x90): multiple definition of `CLSID_StdURLMoniker'
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_StdURLMoniker[_CLSID_StdURLMoniker]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0xb0): multiple definition of `CLSID_MkProtocol'
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_MkProtocol[_CLSID_MkProtocol]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0xc0): multiple definition of `CLSID_HttpSProtocol'
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_HttpSProtocol[_CLSID_HttpSProtocol]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0xd0): multiple definition of `CLSID_HttpProtocol'
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_HttpProtocol[_CLSID_HttpProtocol]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0xe0): multiple definition of `CLSID_GopherProtocol'
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_GopherProtocol[_CLSID_GopherProtocol]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0xf0): multiple definition of `CLSID_FtpProtocol'
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_FtpProtocol[_CLSID_FtpProtocol]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0x100): multiple definition of `CLSID_FileProtocol'
D:/NoInstallSoftware/CB/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib\libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_FileProtocol[_CLSID_FileProtocol]+0x0): first defined here
collect2.exe: error: ld returned 1 exit status

**Comment by mati865** [comment]
Maybe patches need to be updated?

**Comment by lpoujoulat** [comment]
I don't understand of which patch you are talking. Is it something to do on the MSYS2 server's side, or something I have to do on my side ?

**Comment by mati865** [comment]
MSYS2 wxWidgets have these patches: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-wxwidgets
Especially `wxWidgets-3.0.2-relax-abi-compatibility-gcc.patch` seems important.

**Comment by mati865** [comment]
I don't have time to browse commits related to libuuid but you could try asking on mingw-w64 mailing list or IRC (attach link to this comment https://github.com/Alexpux/MINGW-packages/issues/1712#issuecomment-247562691).

**Comment by lpoujoulat** [comment]
I've checked in mingw-64 and some UUID are defined in two files. I files an issue upstream under number ##563. The fix is rather trivial but I don't how long it takes for Mingw64 ...

**Comment by mati865** [comment]
@lpoujoulat you should write on their public mailing list, it's much more active.

**Comment by lpoujoulat** [comment]
Followed your advice, thanks !

**Comment by mati865** [comment]
Try with this mingw-w64 with David's patch (unpack it, then install both packages with `pacman -U`):
[mingw-w64-patched-git.zip](https://github.com/Alexpux/MINGW-packages/files/502736/mingw-w64-patched-git.zip)

**Comment by lpoujoulat** [comment]
Just tried with the same result:
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-uuid.o):uuid.c:(.rdata+0x90): multiple definition of `CLSID_StdURLMoniker'
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_StdURLMoniker[CLSID_StdURLMoniker]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-uuid.o):uuid.c:(.rdata+0xb0): multiple definition of `CLSID_MkProtocol'
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_MkProtocol[CLSID_MkProtocol]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-uuid.o):uuid.c:(.rdata+0xc0): multiple definition of `CLSID_HttpSProtocol'
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_HttpSProtocol[CLSID_HttpSProtocol]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-uuid.o):uuid.c:(.rdata+0xd0): multiple definition of `CLSID_HttpProtocol'
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_HttpProtocol[CLSID_HttpProtocol]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-uuid.o):uuid.c:(.rdata+0xe0): multiple definition of `CLSID_GopherProtocol'
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_GopherProtocol[CLSID_GopherProtocol]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-uuid.o):uuid.c:(.rdata+0xf0): multiple definition of `CLSID_FtpProtocol'
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_FtpProtocol[CLSID_FtpProtocol]+0x0): first defined here
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-uuid.o):uuid.c:(.rdata+0x100): multiple definition of `CLSID_FileProtocol'
D:/NoInstallSoftware/CB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libuuid.a(lib64_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_FileProtocol[CLSID_FileProtocol]+0x0): first defined here
collect2.exe: error: ld returned 1 exit status

**Comment by zelid** [comment]
The problem still exists. The same case:

```
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0x90): multiple definition of `CLSID_StdURLMoniker'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_StdURLMoniker[_CLSID_StdURLMoniker]+0x0): first defined here
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0xb0): multiple definition of `CLSID_MkProtocol'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_MkProtocol[_CLSID_MkProtocol]+0x0): first defined here
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0xc0): multiple definition of `CLSID_HttpSProtocol'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_HttpSProtocol[_CLSID_HttpSProtocol]+0x0): first defined here
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0xd0): multiple definition of `CLSID_HttpProtocol'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_HttpProtocol[_CLSID_HttpProtocol]+0x0): first defined here
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0xe0): multiple definition of `CLSID_GopherProtocol'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_GopherProtocol[_CLSID_GopherProtocol]+0x0): first defined here
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0xf0): multiple definition of `CLSID_FtpProtocol'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_FtpProtocol[_CLSID_FtpProtocol]+0x0): first defined here
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-uuid.o):uuid.c:(.rdata+0x100): multiple definition of `CLSID_FileProtocol'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libuuid.a(lib32_libuuid_a-extras-uuid.o):extras-uuid.c:(.rdata$CLSID_FileProtocol[_CLSID_FileProtocol]+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:14064: /home/Alex/libs/wxWidgets-3.1.0-build-release-shared/lib/wxmsw310u_gcc_custom.dll] Error 1

```

Any workaround so far?

**Comment by lpoujoulat** [comment]
I have found a workaround. Just pass the  --allow-multiple-definition option to ld (use the -Wl, gcc option for that). 

This will let you compile wxWidgets. Anyway, it is just a workaround, not a real solution ...

**Comment by zelid** [comment]
@lpoujoulat Thanks a lot! `-Wl,--allow-multiple-definition` really helped.

This is my final configure that worked fine with the linker hack:

```
 ../wxWidgets-3.1.0/configure --prefix=/home/Alex/libs/wxWidgets-3.1.0-build-release-shared --enable-unicode --enable-shared --with-cxx=14  --enable-cxx11 --enable-monolithic --with-opengl  --enable-webviewie   --enable-stl --enable-std_string --enable-std_iostreams LDFLAGS=-Wl,--allow-multiple-definition
```

**Comment by mati865** [comment]
You should write to MinGW-w64 mailing list.

**Comment by lpoujoulat** [comment]
I did, but there is no fix for now. I guess I will have to propose a patch ...

**Comment by golgepapaz** [comment]
@lpoujoulat did you send a patch to mingw-w64 for this problem? I also need a resolution to this problem..

**Comment by lpoujoulat** [comment]
No, not yet. I'm too busy at the moment ...

**Comment by nezos** [comment]
Same issue with MinGW64 v6.3.0

The workaround suggested helped though.

**Comment by revelator** [comment]
Carefull using that flag, it will propagate down to every source you link to wxwidgets. 
I had the unfortunate experience while fighting a similar bug with boost :/

**Comment by guy-rouillier** [comment]
I just ran into this problem using MingW-w64 7.1.0.  I did two different builds of wxWidgets: one monolithic and one with split DLLs.  This problem only occurs with the monolithic build. I need to do some build tracing to determine how the split build avoids this issue, but perhaps wxWidgets can avoid this problem through some well-placed defines.  I'll investigate and report back.

**Comment by zufuliu** [comment]
Fixed in MinGW-w64:
https://sourceforge.net/p/mingw-w64/mingw-w64/ci/57311fedb4960ad7d8b444b34c06a41f32b13702/

**Comment by revelator** [comment]
Tim at the codeblocks forums had a patch ready for fixing this in the mingw-w64 runtime, but he had problems finding the right place to post it so i offered my help. The patch is by him though it states it's by me because i had to do a git-format to make it apply. It should be fixed now though :)

**Comment by zaleksf** [comment]
This problem still exists in mingw-w64 version x86_64-7.2.0-posix-seh-rt_v5-rev0, when attempting to build the WxWidgets 3.0.x branch.

How long do you think it will take for the developers to get your patch into the mingw-w64 code base, and the binaries released? I hadn't planned on building mingw-w64 from source, but maybe I will need to learn how to do that in order to get the proper mingw-w64 functionality relatively soon.

The LDFLAGS=-Wl,--allow-multiple-definition flags do work as a work-around, but I'm trying to avoid the associated risks.

**Comment by stahta01** [comment]
No one submitted a package and since wxWidgets 3.1 is a development release I did not yet submit my package I have created. I am still working on the proper way to get 3.1.1 and 3.0.4 to coexist.

Tim S.

**Comment by stahta01** [comment]
I have submitted a pull request #4748

**Comment by oltolm** [comment]
https://github.com/msys2/MINGW-packages/pull/4748 was merged. Can we close this?
