### ISSUE TITLE
Building a program with cmake+LLVM issue a problem

### ISSUE THREAD

**Issue by ChinouneMehdi** [Alexpux/MINGW-packages#2928]
I tried to build a program that requires LLVM but cmake issue this error:

> CMake Error at C:/msys64/mingw64/lib/cmake/llvm/LLVMExports.cmake:662 (message):
>   The imported target "PollyISL" references the file
>      "C:/msys64/mingw64/lib/libPollyISL.a"
>   but this file does not exist.  Possible reasons include:
>   * The file was deleted, renamed, or moved to another location.
>   * An install or uninstall procedure did not complete successfully.
>   * The installation package was faulty and contained
>      "C:/msys64/mingw64/lib/cmake/llvm/LLVMExports.cmake"
>   but not all the files it references.

I think this problem appears only with LLVM 5.0.0
MinGW-LLVM Version : 5.0.0-2

**Comment by mati865** [comment]
Try `pacman -S mingw-w64-x86_64-polly`. Maybe llvm depends on it.

**Comment by ChinouneMehdi** [comment]
Thanks @mati865 you suggestion solves the problem.

**Comment by mati865** [comment]
Thanks for testing, it should be fixed in next release (5.0.0-2 doesn't count).

**Comment by Alexpux** [comment]
Already uploaded new packages

**Comment by ChinouneMehdi** [comment]
Sorry but it looks like the problem still not solved. cmake generate the Makefiles. but it fails to build:

> CMakeFiles/program.dir/objects.a(cc1_main.cpp.obj):cc1_main.cpp:(.text+0x59c): undefined reference to `polly::initializePollyPasses(llvm::PassRegistry&)'
> collect2.exe: error: ld returned 1 exit status
> make[2]: *** [tools/driver/CMakeFiles/program.dir/build.make:239: bin/program.exe] Error 1
> make[1]: *** [CMakeFiles/Makefile2:4387: tools/driver/CMakeFiles/program.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2

**Comment by mati865** [comment]
Without way to reproduce I'm in the dark.
Try to pass `-lPolly` to the compiler.

**Comment by ChinouneMehdi** [comment]
I think the problem is due of the patch : '0801-Don-t-build-LLVMPolly-on-WIN32.patch'

**Comment by mati865** [comment]
I still need more details.
Is it static or dynamic build, gcc or clang?

**Comment by ChinouneMehdi** [comment]
I tried to build this modified clang : [(https://github.com/flang-compiler/clang)]
After building my own LLVM everything goes smoothly.

**Comment by mati865** [comment]
Still there is almost no info here.
1. Have you manually added Polly to your LLVM build?
2. Is your LLVM build statically or dynamically?
3. Is your project build statically or dynamically?

**Comment by ChinouneMehdi** [comment]
I have built LLVM with these commands :
>mkdir build && cd build
>cmake -G "MSYS Makefiles" -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/c/Programs/clang ..
>make -j

and the modified Clang with
>export PATH=/c/Programs/clang/bin:$PATH
>mkdir build && cd build
>cmake -G "MSYS Makefiles"  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/c/Programs/clang ..
>make -j

**Comment by mati865** [comment]
So you build LLVM without Polly as it isn't included by default.

Your LLVM and flag are build statically (it is default setting) and `0801-Don-t-build-LLVMPolly-on-WIN32.patch` affects only dynamic builds (`llvmPolly.dll` clashes with `LLVM_LINK_LLVM_DYLIB=ON` setting).

Tomorrow I'll test flang and hope to upload LLVM without Polly built in for you to try.

**Comment by mati865** [comment]
@ChinouneMehdi compiling flang from `flang_release_50` branch failed with:
```
[100%] Linking CXX shared library ../../bin/libclang.dll
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldl
collect2.exe: error: ld returned 1 exit status
```
And CMake was configured with: `cmake -G "MSYS Makefiles" -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Release ..`

Could you tell at which percent error occurred and upload file `build\CMakeCache.txt`?

I have a theory about this issue, run: 
```CC=clang CXX=clang++ cmake -G "MSYS Makefiles" -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Release ..
make -j
```

**Comment by ChinouneMehdi** [comment]
I have encountered this problem and i solved it by installing:
> pacman -S mingw-w64-x86_64-dlfcn

I think the problem occurred at 100% when trying to build (linking) `clang.exe` and `libclang`

**Comment by mati865** [comment]
@ChinouneMehdi this should work fine:
https://drive.google.com/file/d/0B6ARjZmUNVOYSEZ6TUpQZktaTkE/view?usp=sharing
https://drive.google.com/file/d/0B6ARjZmUNVOYVVRXT0Z1YWFycFk/view?usp=sharing

Install those 2 files with `pacman -U `.

**Comment by ChinouneMehdi** [comment]
Thank you, Now it works.
