### ISSUE TITLE
ruby-2.5.0 breaks asciidoctor

### ISSUE THREAD

**Issue by angelog0** [Alexpux/MINGW-packages#3338]
Just now I discovered this with `mingw-w64-x86_64-ruby 2.5.0-1`:

asciidoctor WSL-install.adoc
C:/msys64/mingw64/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem asciidoctor (>= 0.a) with executable asciidoctor (Gem::GemNotFoundException)
        from C:/msys64/mingw64/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
        from C:/msys64/mingw64/bin/asciidoctor:22:in `<main>'

reverting to `mingw-w64-x86_64-ruby-2.4.0-1` fixes the issue...

  Angelo

**Comment by JPeterMugaas** [comment]
https://github.com/Alexpux/MINGW-packages/pull/3340 should fix this issue.  The binary has to be rebuilt for each new Ruby version.

**Comment by angelog0** [comment]
Confirmed. I have rebuilt asciidoctor and now it works.

**Comment by angelog0** [comment]
I don't know how you have rebuilt asciidoctor 1.5.5-2 but it still does not work

$ asciidoctor WSL-install.adoc
-bash: /mingw64/bin/asciidoctor: C:/building/msys64/mingw64/bin/ruby.exe: interprete errato: No such file or directory

my builds of 1.5.5-1 and 1.5.5-2 work just fine...

**Comment by Alexpux** [comment]
Seems this is because hardcoded paths in ruby scripts. See PATH in error message

**Comment by angelog0** [comment]
I have seen... Why then my builds work? I thin you have something wron in your(s) systems. All I did is this:

cd /tmp/
mkdir mingw-w64-asciidoctor
cd mingw-w64-asciidoctor
wget https://raw.githubusercontent.com/Alexpux/MINGW-packages/master/mingw-w64-asciidoctor/PKGBUILD

MINGW_INSTALLS=mingw64 makepkg-mingw -sLf

pacman -U mingw-w64-x86_64-asciidoctor-1.5.5-2-any.pkg.tar.xz

In MinGW64 shell:

cd ~/WSL
asciidoctor WSL-install.adoc

it generates the .html file which I can open in the browser...

So, why your build have hardcoded that directory?

**Comment by mati865** [comment]
@angelog0 both builds have hardcoded directories, the difference is your build have correct path for your system.

**Comment by angelog0** [comment]
Sorry, I closed inadvertently the issue...

**Comment by angelog0** [comment]
@Alexpux wrote:

> both builds have hardcoded directories, the difference is your build have correct path for your system

So, is this an issue or not? Does that mean each time there is an asciidoctor update I have to rebuilt it to get it working?

**Comment by mati865** [comment]
It's common issue when porting programs for Windows, paths have to be fixed so it works for everyone.

**Comment by JPeterMugaas** [comment]
Alright, I think I may have a fix for asciidoc and invalid pathes.  I even went further and fixed the batch files.

https://github.com/Alexpux/MINGW-packages/pull/3350

Let me know if this works.

**Comment by JPeterMugaas** [comment]
It is an issue that I did not see because I was building on my own system.  Just review what I have.

**Comment by angelog0** [comment]
Now the update seems to work as expected :)

Maybe you can close this issue if you do not want to add other comments.

Thanks

**Comment by JPeterMugaas** [comment]
My comments at this point are in the PKGBUILD file itself where I explain the logic behind some search and replacements.  So I think it should be closed as well.

**Comment by angelog0** [comment]
@JPeterMugaas wrote:

> So I think it should be closed as well.

done!
