### ISSUE TITLE
"Too many open files" and binutils 2.31.1-1

### ISSUE THREAD

**Issue by slomp** [Alexpux/MINGW-packages#4317]
I'm getting "Too many open files" when building LLVM/clang (release_60 branch) with the most recent version of binutils (2.31.1-1).
Running ulimit -n 3200 did not help.
Downgrading to [2.30-2](http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-binutils-2.30-2-any.pkg.tar.xz) solved the problem (without even needing to tweak the limit, which defaults to 256).

**Comment by mingwandroid** [comment]
You probably need to reduce the level of parallelism in the call to make

**Comment by slomp** [comment]
Already tried doing that to with `-j1` and the same problem persisted.

**Comment by mingwandroid** [comment]
Oh weird.

**Comment by slomp** [comment]
For reference, here's a similar 2016 discussion on the issue:
https://sourceforge.net/p/msys2/mailman/message/34988811/
That's where I got the hint that the problem was related to binutils.

**Comment by mingwandroid** [comment]
Yeah, it does seem to be binutils running into the limit.

**Comment by mingwandroid** [comment]
You should report this at binutil's bugzilla really.

**Comment by slomp** [comment]
Oh, I see, so does that mean that you managed to also reproduce the issue on a non-MinGW system?

If that's the case, I'll go ahead and file a bug on GNU binutils, providing this thread as a reference.

**Comment by Alexpux** [comment]
Will downgrade binutils package to 2.30

**Comment by slomp** [comment]
FYI, a new post on the bug report thread suggests that the bug has been fixed on binutils master:
https://sourceware.org/bugzilla/show_bug.cgi?id=23573

**Comment by Alexpux** [comment]
Will see when new binutils will be released

**Comment by Alexpux** [comment]
@slomp at least no one patch mentioned in bug report doesnt resolve the issue

**Comment by revelator** [comment]
the fix on linux is setting /etc/security limits higher, but i doubt this would work here.
Also i just tested the new binutils-2.32 and it still fails on building clang with too many open files despite the dev saying its fixed :(.  Back to the drawing board with this one it seems.

**Comment by slomp** [comment]
Yeap, clang is resource hog when it comes to building it :(

**Comment by manisandro** [comment]
FYI, this is fixed in master, and the commit which fixes this is https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=999d6dff80fab12d22c2a8d91923db6bde7fb3e5

**Comment by slomp** [comment]
Awesome, thanks!

**Comment by Alexpux** [comment]
@slomp I confirm that patch solve issue, will update binutils in repo soon.
