### ISSUE TITLE
clang++ strtold() segmentation fault

### ISSUE THREAD

**Issue by vpetrigo** [Alexpux/MINGW-packages#722]
Hello,

I have met an issue with segmentation fault in program which was built by clang.
Here is the code which represents the bug:
```cpp
#include <iostream>                         
#include <string>                           
                                            
int main() {                                
    char *ptr;                              
    const char *s = "1.23";                         
    long double ld = std::strtold(s, &ptr);                                           
    std::cout << ld;
                                              
    return 0;                               
}                                                                       
```
With the current `g++ (5.2.0)` there is no problem, but clang has. 
I use clang from mingw64 repo:
```
clang version 3.6.2 (tags/RELEASE_362/final)
Target: x86_64-w64-windows-gnu
Thread model: posix
```

I also tried to build the latest available clang , but it has the same effect:
```
clang version 3.8.0 (trunk)
Target: x86_64-w64-windows-gnu
Thread model: posix
```

**Comment by martell** [comment]
Hello @vpetrigo,

First of all I can reproduce the segmentation fault you have above.
If you replace the line above however with
char s[] = "1.23";
It does not crash, it does however output 0 instead of 1.23

I'm currently getting code merged for lld and merging patches to have mingw-w64 to be built with clang without gcc so I won't be able to get to fixing this until later in the week.

Looking at this there could be a few different causes.
I am going to most likely say however that it is quite possibly related to differences between libc++ and libstdc++.

I am going to go out on a limb and say that libstdc++ assumes memory to be NULL'd by the compiler while libc++ takes this into account.
Have you tried this on a linux box with clang using libstdc++?
This might not be windows specific.

Less likely but possibly is bad code generation.
If you can dump the asm code generation of what clang and gcc both produce you might be able to find the cause.

If not as I said I'll have a look at this later on in the week :)

Kind Regards
Martell

**Comment by oscarfv** [comment]
[I'm not the OP]

@martell :
> Have you tried this on a linux box with clang using libstdc++?
> This might not be windows specific.

Just tried on Linux with clang svn 243155 (Jul 24), libstdc++, and the output is the expected `1.23`.

**Comment by martell** [comment]
@oscarfv Thanks for narrowing this down.

@vpetrigo 
I will test on libc++ on windows when I finish up on the other clang related stuff I am working on.
If it fails there then it is most likely bad code generation which we will have to file a bug on llvm for.

Kind Regards
Martell

**Comment by vpetrigo** [comment]
Hello, @martell.
Thank you for your responce. I also tested on the linux machine with `clang-3.6` from this repo:
```
deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main
deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main
```
and with the most latest trunk version. I use `libstdc++` and have not met any issue. I will try to build `libc++` for `mingw` and will tell you if I am investigate something new.

Best regards,
Vladimir

**Comment by vpetrigo** [comment]
@martell I have found one more case when clang++ gives `Segmentation fault` error:
```cpp
#include <sstream>
#include <iostream>

long double foo(long double v) {
    std::stringstream ss;
    
    ss << v;
    
    ss.precision(6);
    
    ss >> v;
    
    return v;
}

int main() {
    long double a = 10.1238127638712638;
    
    std::cout << foo(a) << std::endl;
    
    return 0;
}
```

**Comment by martell** [comment]
@vpetrigo Can you create an issue over at https://llvm.org/bugs/ with this testcase and assign it to me.

Kind Regards
Martell

**Comment by vpetrigo** [comment]
@martell yes, already did it.

**Comment by martell** [comment]
I fixed it upstream
http://reviews.llvm.org/rL245084

**Comment by mingwandroid** [comment]
Fantastic work @martell

**Comment by vpetrigo** [comment]
@martell , thank you a lot!
As I understand the last clang in the msys2 repository does not use this fix, does it? Because code from the first message still throws **Segmentation fault**.

**Comment by martell** [comment]
hmm very strange.

I only just found out about the new 3.7.0 packages in msys2 just an hour ago.
I didn't build them myself but the PKGBUILD looks good to me.

Now that we have a 3.7.0 I can see a lot clearer what is missing though.

Whatever bugs you find keep them coming I'll make sure to crush them all. :)

Reopening: I will look at this again.

**Comment by vpetrigo** [comment]
@martell I've found another case when the segmentation fault happens.
Take a look at such code:
```cpp
#include <iostream>
#include <unordered_map>

int main() {
    std::unordered_map<std::string, int> um {{"One", 1}, {"Two", 2}};
    
    for (auto& i : um) {
        std::cout << i.first << ' '
            << i.second << std::endl;
    }
    
    return 0;
}
```
I'm not sure if it is connected with the bug you fixed, but it looks like `unordered_map` doesn't work with current `clang++` version at all.

**Comment by vpetrigo** [comment]
@martell I've built the last svn version of `clang`:
```
clang version 3.8.0 (trunk 246967) (llvm/trunk 246966)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:\Users\pve\Libraries\llvm\build\bin
```
But the issue happens anyway. There is the stacktrace below:
```
[New Thread 33416.0x43a4]

Program received signal SIGSEGV, Segmentation fault.
strtold (s=0x22fe48 "\001", se=0x4a2f80) at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/misc/strtold.c:395
395     C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/misc/strtold.c: No such file or directory.
```
How might it be that all is ok with `g++`, but with `clang++` it says that there is no some file?

**Comment by a2flo** [comment]
seems like http://llvm.org/viewvc/llvm-project?view=revision&revision=245620 reverted it accidentally.
X86_64TargetInfo does indeed set the correct LongDoubleWidth and LongDoubleAlign value (128), but it doesn't set LongDoubleFormat to x87DoubleExtended.

**Comment by martell** [comment]
yes but that is extended from X86TargetInfo
Which sets LongDoubleFormat = &llvm::APFloat::x87DoubleExtended;

Something strange is going on however because it was working for me at one point when I patched it :/

**Comment by a2flo** [comment]
ah, didn't see that.
but yeah, it's still broken (or broken again ...).

	long double val = 123.456;
	cout << "alignof: " << alignof(long double) << endl;
	cout << "sizeof: " << sizeof(long double) << endl;
	cout << "val: " << val << endl;

with gcc 5.2.0:

	alignof: 16
	sizeof: 16
	val: 123.456

with clang 3.7.0:

	alignof: 16
	sizeof: 12
	val: -1.68953e+4672

(both are msys packages btw ... will be compiling this myself now and see if I can fix it ...)

**Comment by martell** [comment]
An "objdump -d" of the object files should reveal the differences and what the cause is.
I would really appreciate that as my spare time is very little atm :(

**Comment by a2flo** [comment]
not easy to figure out, objdump produces ~130kb files (yay for stl code ...) and it's tricky to produce a simple C-only example, since this problem will apparently only occur when there is some long double interop between clang code and gcc code. (also: printf of long doubles on mingw seems to be broken/not implemented?)

but I'd assume that it has something to do with the fact that clang thinks the size of a long double is 12 and gcc thinks it's 16. that is, for single values. an array of long doubles will have the same size (16 * N) and bit values for both. gcc pads the last 4 bytes with 00 btw.

**Comment by martell** [comment]
hey guys this is now closed.
Reid one of the clang developers was kind enough to spend some time with me today on irc to fix it
http://reviews.llvm.org/rL251567

**Comment by vpetrigo** [comment]
@martell thank you!
